app.config:
    charset:       UTF-8
    error_handler: null
    #csrf_secret:   xxxxxxxxxx
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:
        escaping:       htmlspecialchars
        #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime: 3600

## Twig Configuration
#twig.config:
#    auto_reload: true

## Doctrine Configuration
#doctrine.dbal:
#    dbname:   xxxxxxxx
#    user:     xxxxxxxx
#    password: ~
doctrine.dbal:
  default_connection:       default
  connections:
    default:
      driver:               PDOMySql
      dbname:               web3cms_r34
      user:                 web3cmsuser
      password:             web3cmspass
      host:                 localhost
      port:                 ~
doctrine.orm: ~

## Swiftmailer Configuration
#swiftmailer.config:
#    transport:  smtp
#    encryption: ssl
#    auth_mode:  login
#    host:       smtp.gmail.com
#    username:   xxxxxxxx
#    password:   xxxxxxxx
